global:
  resolve_timeout: 5m

route:
  receiver: default-team
  group_by: [alertname, cluster, service]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - match:
        severity: critical
      receiver: pagerduty-critical

    - match:
        team: database
      receiver: database-team

receivers:
  - name: default-team
    webhook_configs:
      - url: http://flask-app:5000/alert
        send_resolved: true

  - name: pagerduty-critical
    webhook_configs:
      - url: http://flask-app:5000/alert
        send_resolved: true

  - name: database-team
    webhook_configs:
      - url: http://flask-app:5000/alert
        send_resolved: true

inhibit_rules:
  - source_match:
      alertname: NodeDown
    target_match_re:
      alertname: (ServiceDown|DiskWarning)
    equal: [instance]
